//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace venue365.securityprovider.SecurityAgentService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SecurityAgentService.ISecurityAgent")]
    public interface ISecurityAgent {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityAgent/Add", ReplyAction="http://tempuri.org/ISecurityAgent/AddResponse")]
        void Add(string key, string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityAgent/Add", ReplyAction="http://tempuri.org/ISecurityAgent/AddResponse")]
        System.Threading.Tasks.Task AddAsync(string key, string input);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityAgent/Get", ReplyAction="http://tempuri.org/ISecurityAgent/GetResponse")]
        string Get(string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISecurityAgent/Get", ReplyAction="http://tempuri.org/ISecurityAgent/GetResponse")]
        System.Threading.Tasks.Task<string> GetAsync(string key);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISecurityAgentChannel : venue365.securityprovider.SecurityAgentService.ISecurityAgent, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SecurityAgentClient : System.ServiceModel.ClientBase<venue365.securityprovider.SecurityAgentService.ISecurityAgent>, venue365.securityprovider.SecurityAgentService.ISecurityAgent {
        
        public SecurityAgentClient() {
        }
        
        public SecurityAgentClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SecurityAgentClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityAgentClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SecurityAgentClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Add(string key, string input) {
            base.Channel.Add(key, input);
        }
        
        public System.Threading.Tasks.Task AddAsync(string key, string input) {
            return base.Channel.AddAsync(key, input);
        }
        
        public string Get(string key) {
            return base.Channel.Get(key);
        }
        
        public System.Threading.Tasks.Task<string> GetAsync(string key) {
            return base.Channel.GetAsync(key);
        }
    }
}
